name: exome-results-browsers
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - pre-commit
  - nodejs
  - yarn
  - pip:
      - click
      - hail
      - pyarrow
      - protobuf==3.20.1
      - Jinja2==3.0.3
      - google-cloud-storage
      - google-cloud-bigquery
