name: exome-results-browsers
channels:
  - cpg
  - bioconda/osx-64
  - conda-forge/osx-64
dependencies:
  - python >= 3.7,<3.8
  - pip
  - pandas
  - numpy
  - scikit-learn
  - jupyterlab
  - pre-commit
  - hail
  - samtools
  - hstlib
  - nodejs
  - yarn
  - pip:
      - black==21.7b0
      - pylint==2.9.5
      - umap-learn
      - bokeh
      - seaborn
      - requests
