name: exome-results-browsers
channels:
  - cpg
  - bioconda
  - conda-forge
dependencies:
  - python >= 3.7,<3.8
  - pip
  - pandas
  - pre-commit
  - hail
  - nodejs
  - yarn
  - pip:
      - black==21.7b0
      - pylint==2.9.5
      - google-cloud-storage
      - google-cloud-bigquery
