name: exome-results-browsers
channels:
  - cpg
  - bioconda
  - conda-forge
dependencies:
  - python
  - pip
  - pre-commit
  - nodejs
  - yarn
  - pip:
      - black
      - pylint
      - jupyter
      - notebook
      - fastparquet
      - pyspark
      - pyarrow
      - pandas
      - hail
      - google-cloud-storage
      - google-cloud-bigquery
