name: Deploy web server
on:
  push:
    branches:
      - production
jobs:
  deploy_server:
    runs-on: ubuntu-latest

    env:
      DOCKER_BUILDKIT: 1
      BUILDKIT_PROGRESS: plain
      CLOUDSDK_CORE_DISABLE_PROMPTS: 1
      CI_ENVIRONMENT: production
      DOCKER_IMAGE: australia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_ARTIFACT_REPO }}/${{ secrets.GCP_IMAGE_NAME }}-production:${{ github.sha }}

    steps:
      - name: 'checkout repo'
        uses: actions/checkout@v2

      - name: 'gcloud setup'
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: 'gcloud docker auth'
        run: |
          gcloud auth configure-docker australia-southeast1-docker.pkg.dev
      - name: 'build image'
        run: |
          docker build --tag $DOCKER_IMAGE .
      - name: 'push image'
        run: |
          docker push $DOCKER_IMAGE

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: ${{ secrets.GCP_CLOUD_RUN_SERVICE }}-${{ env.CI_ENVIRONMENT }}
          image: ${{ env.DOCKER_IMAGE }}
          region: australia-southeast1
          credentials: ${{ secrets.GCP_SA_KEY }}
          env_vars: RESULTS_DATA_DIRECTORY="${{ secrets.GCP_BUCKET }}"

      - name: Use Output
        run: curl "${{ steps.deploy.outputs.url }}"
