name: Deploy web server

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy_server:
    runs-on: ubuntu-latest

    env:
      DOCKER_BUILDKIT: 1
      BUILDKIT_PROGRESS: plain
      CLOUDSDK_CORE_DISABLE_PROMPTS: 1
      DOCKER_IMAGE_BASE: australia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_ARTIFACT_REPO }}

    steps:
      - name: 'checkout repo'
        uses: actions/checkout@v2

      - name: Create dummy build.env file
        run: touch build.env

      - name: Set deployment type
        run: |
          if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
            echo "DEPLOYMENT_TYPE=prod" >> $GITHUB_ENV
          else
            echo "DEPLOYMENT_TYPE=dev" >> $GITHUB_ENV
          fi
          echo "Setting up a ${DEPLOYMENT_TYPE} deployment"
          echo "RELEASE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Set Docker image
        run: |
          echo "DOCKER_IMAGE=$DOCKER_IMAGE_BASE/browser-$DEPLOYMENT_TYPE:$RELEASE_TAG" >> $GITHUB_ENV

      - name: 'gcloud setup'
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_DEPLOY_SA_KEY }}

      - name: 'gcloud docker auth'
        run: |
          gcloud auth configure-docker australia-southeast1-docker.pkg.dev
      - name: 'build image'
        run: |
          docker build --tag $DOCKER_IMAGE .
      - name: 'push image'
        run: |
          docker push $DOCKER_IMAGE

      - name: 'gcloud run deploy'
        run: |
          gcloud run deploy browser-$DEPLOYMENT_TYPE \
          --memory=1Gi \
          --region=australia-southeast1 \
          --platform=managed \
          --set-env-vars=RESULTS_DATA_DIRECTORY=${{ secrets.GCP_BUCKET }} \
          --service-account=${{ secrets.GCP_CLOUD_RUN_SA }} \
          --image=$DOCKER_IMAGE \
          --no-allow-unauthenticated
